#!/bin/bash
# Periodically re-run validate_run_all.py for a run directory to pick up new
# programs as they are generated by a still-running experiment.
#
# validate_run_all.py already skips already-evaluated nodes, so re-running it
# just processes whatever is new in the journal since the last check.
#
# Usage (directly):
#   bash watch_and_test.sh --log-dir /share/j_sun/as2637/logs/clevr_count/aSSL_0_1_metric_prior/k2/seed0/aira/1111
#   bash watch_and_test.sh --log-dir ... --interval 1800   # seconds (default: 1800 = 30 min)
#   bash watch_and_test.sh --log-dir ... --max-rounds 48   # stop after N rounds (default: unlimited)
#
# Usage (via SLURM — see submit_watch_test.sh):
#   bash submit_watch_test.sh --log-dir ...

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LOG_DIR=""
INTERVAL=1800   # 30 minutes
MAX_ROUNDS=-1   # -1 = unlimited

while [[ $# -gt 0 ]]; do
    case "$1" in
        --log-dir)    LOG_DIR="$2";    shift 2 ;;
        --interval)   INTERVAL="$2";  shift 2 ;;
        --max-rounds) MAX_ROUNDS="$2"; shift 2 ;;
        *) echo "Unknown arg: $1"; exit 1 ;;
    esac
done

if [[ -z "$LOG_DIR" ]]; then
    echo "ERROR: --log-dir is required"
    exit 1
fi

echo "=== watch_and_test.sh ==="
echo "  log-dir:    $LOG_DIR"
echo "  interval:   ${INTERVAL}s"
echo "  max-rounds: $([ "$MAX_ROUNDS" -eq -1 ] && echo unlimited || echo "$MAX_ROUNDS")"
echo "  started:    $(date)"
echo ""

round=0
while true; do
    round=$((round + 1))
    echo "──────────────────────────────────────────"
    echo "Round $round — $(date)"
    echo "──────────────────────────────────────────"

    python "$SCRIPT_DIR/validate_run_all_back.py" --log-dir "$LOG_DIR" || \
        echo "WARNING: validate_run_all_back.py exited with error on round $round"

    if [[ "$MAX_ROUNDS" -ne -1 && "$round" -ge "$MAX_ROUNDS" ]]; then
        echo "Reached max rounds ($MAX_ROUNDS). Stopping."
        break
    fi

    echo "Sleeping ${INTERVAL}s until next check…"
    sleep "$INTERVAL"
done

echo "=== watch_and_test.sh done at $(date) ==="
